"""add description

Revision ID: e3c9a7e64c26
Revises: 73053509127a
Create Date: 2021-10-15 21:18:40.047338

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e3c9a7e64c26'
down_revision = '73053509127a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_task_task_description'), 'task', ['task_description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_task_description'), table_name='task')
    op.drop_column('task', 'task_description')
    # ### end Alembic commands ###
